### PR TITLE
`core::crypto`: features cleanup in tests

### PR DESCRIPTION
**Pull request by michalkucharczyk**
There are three features that affect how `crypto` module is compiled: `std`, `full_crypto` and `serde`.

Following invocations are now failing:
```
cargo test --no-default-features --features="full_crypto"
cargo test --no-default-features --features="full_crypto,serde"
cargo test --no-default-features --features="serde"
cargo test --no-default-features
```

This PR adds the features to the test, so these commands are working properly.

Some groundwork for: https://github.com/paritytech/polkadot-sdk/issues/1984

### CODE REVIEW

File: substrate/primitives/core/Cargo.toml [hunk 1]
```diff
@@ -132,6 +132,7 @@ serde = [
 	"secrecy/alloc",
 	"sp-core-hashing",
 	"sp-storage/serde",
+	"sp-runtime-interface/disable_target_static_assertions",
```
Comment (michalkucharczyk) [inline substrate/primitives/core/Cargo.toml:135]: This probably should not be here. W/o compilation fails:
```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
  --> substrate/primitives/runtime-interface/src/impls.rs:45:1
   |
45 | assert_eq_size!(usize, u32);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: source type: `usize` (64 bits)
   = note: target type: `u32` (32 bits)
   = note: this error originates in the macro `assert_eq_size` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by burdges** [comment]
Is serde still relevant?

File: substrate/primitives/core/Cargo.toml (hunk 1 above)
Comment (bkchr) [reply substrate/primitives/core/Cargo.toml:134]: Substrate currently assumed that `no_std == arch::wasm32`. Shitty, I know, but that is currently the assumption.

File: .gitlab/pipeline/test.yml [hunk 2]
```diff
@@ -157,6 +157,23 @@ test-linux-stable-slow:
...
+    - .pipeline-stopper-artifacts
+  variables:
+    RUST_TOOLCHAIN: stable
+    # Enable debug assertions since we are running optimized builds for testing
+    # but still want to have debug assertions.
+    RUSTFLAGS: "-Cdebug-assertions=y -Dwarnings"
+  script:
+    - time cargo test --release -p sp-core --no-default-features --features="full_crypto"
+    - time cargo test --release -p sp-core --no-default-features --features="full_crypto,serde"
+    - time cargo test --release -p sp-core --no-default-features --features="serde"
```
Comment (bkchr) [inline .gitlab/pipeline/test.yml:175]: Do we actually need to test here? Wouldn't `check` be enough?

File: substrate/primitives/core/Cargo.toml (hunk 1 above)
Comment (koute) [reply substrate/primitives/core/Cargo.toml:134]: Yes, that assert should be changed to check for `wasm32` and not for `no_std`, and then you won't need to disable it.

...as Basti said, the current assumption everywhere is that no_std equals WASM, which, uh, I guess I'll have to fix soon-ish since I'll be wanting to get the RISC-V based runtimes working. :P

File: .gitlab/pipeline/test.yml (hunk 2 above)
Comment (michalkucharczyk) [reply .gitlab/pipeline/test.yml]: https://github.com/paritytech/polkadot-sdk/pull/1983/commits/e3fa4a591241a4f16bba817baad45f120429254c

Comment (bkchr) [reply .gitlab/pipeline/test.yml]: Yeah good idea.

File: substrate/primitives/core/Cargo.toml (hunk 1 above)
Comment (bkchr) [reply substrate/primitives/core/Cargo.toml]: Yeah good idea.

File: substrate/primitives/core/src/ecdsa.rs [hunk 3]
```diff
@@ -569,6 +577,7 @@ mod test {
 	}
 
 	#[test]
+	#[cfg(feature = "std")]
```
[the remark this answers is not in the document]
Comment (michalkucharczyk) [reply substrate/primitives/core/src/ecdsa.rs:580]: Yes. I want `time cargo test --release -p sp-core --no-default-features --features="serde"` to be executed correctly.

[the remark this answers is not in the document]
Comment (bkchr) [reply substrate/primitives/core/src/ecdsa.rs:580]: But you don't run this anymore? And serde is mainly about testing that it compiles?

[the remark this answers is not in the document]
Comment (michalkucharczyk) [reply substrate/primitives/core/src/ecdsa.rs:580]: I want to run it locally. I want to have ability to test the `sp-core` with the different feature sets it offers. `serde` was just an example, `full-crypto` or `full-crypto,serde` are the other options.

[the remark this answers is not in the document]
Comment (michalkucharczyk) [reply substrate/primitives/core/src/ecdsa.rs:580]: We have trait methods definition under `std`, so w/o this paricular gate you will get:

`cargo +nightly check --tests --no-default-features --features="full_crypto"`

```
error[E0599]: no function or associated item named `from_full` found for struct `ecdsa::Public` in the current scope
   --> substrate/primitives/core/src/ecdsa.rs:588:12
    |
80  | pub struct Public(pub [u8; PUBLIC_KEY_SERIALIZED_SIZE]);
    | ----------------- function or associated item `from_full` not found for this struct
...
588 |             Public::from_full(
    |                     ^^^^^^^^^ function or associated item not found in `Public`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `sp-core` (lib test) due to previous error
```

[the remark this answers is not in the document]
Comment (bkchr) [reply substrate/primitives/core/src/ecdsa.rs:580]: > We have trait methods definition under `std`, so w/o this paricular gate you will get:
> 
> `cargo +nightly check --tests --no-default-features --features="full_crypto"`

Because you are using `--tests`. Just drop this, these tests only need to work on `std`.

[the remark this answers is not in the document]
Comment (michalkucharczyk) [reply substrate/primitives/core/src/ecdsa.rs:580]: Then this PR does not make sense.

[the remark this answers is not in the document]
Comment (bkchr) [reply substrate/primitives/core/src/ecdsa.rs:580]: I mean checking that it compiles make sense. (without the tests). To ensure that these features compile on their own.
