### ISSUE TITLE
WASM build error after upgrading to stable2503-7

### ISSUE THREAD

**Issue by l0r1s** [paritytech/polkadot-sdk#9282]
### Is there an existing issue?

- [x] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [x] This is not a support question.

### Description of bug

After upgrading SDK for our node from 2412-6 to 2503-7, it is not possible to build the WASM anymore, the following error appears:

```
error[E0463]: can't find crate for `std`
    |
    = note: the `wasm32v1-none` target may not support the standard library
    = note: `std` is required by `thiserror` because it does not declare `#![no_std]`

  error[E0463]: can't find crate for `std`
   --> /Users/loris/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/thiserror-1.0.69/src/aserror.rs:2:5
    |
  2 | use std::error::Error;
    |     ^^^ can't find crate
    |
    = note: the `wasm32v1-none` target may not support the standard library

  error[E0463]: can't find crate for `std`
   --> /Users/loris/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/thiserror-1.0.69/src/display.rs:2:5
    |
  2 | use std::path::{self, Path, PathBuf};
    |     ^^^ can't find crate
    |
    = note: the `wasm32v1-none` target may not support the standard library

  error[E0405]: cannot find trait `Send` in this scope
    --> /Users/loris/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/thiserror-1.0.69/src/aserror.rs:23:41
     |
  23 | impl<'a> AsDynError<'a> for dyn Error + Send + 'a {
     |                                         ^^^^ not found in this scope
     |
  help: consider importing this trait
     |
  1  + use core::marker::Send;
     |

  error[E0405]: cannot find trait `Send` in this scope
    --> /Users/loris/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/thiserror-1.0.69/src/aserror.rs:30:41
     |
  30 | impl<'a> AsDynError<'a> for dyn Error + Send + Sync + 'a {
     |                                         ^^^^ not found in this scope
     |
  help: consider importing this trait
     |
  1  + use core::marker::Send;
     |

  error[E0405]: cannot find trait `Sync` in this scope
    --> /Users/loris/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/thiserror-1.0.69/src/aserror.rs:30:48
     |
  30 | impl<'a> AsDynError<'a> for dyn Error + Send + Sync + 'a {
     |                                                ^^^^ not found in this scope
     |
  help: consider importing this trait
     |
  1  + use core::marker::Sync;
     |

  error[E0405]: cannot find trait `Send` in this scope
    --> /Users/loris/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/thiserror-1.0.69/src/aserror.rs:37:41
     |
  37 | impl<'a> AsDynError<'a> for dyn Error + Send + Sync + UnwindSafe + 'a {
     |                                         ^^^^ not found in this scope
     |
  help: consider importing this trait
     |
  1  + use core::marker::Send;
     |

  error[E0405]: cannot find trait `Sync` in this scope
    --> /Users/loris/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/thiserror-1.0.69/src/aserror.rs:37:48
     |
  37 | impl<'a> AsDynError<'a> for dyn Error + Send + Sync + UnwindSafe + 'a {
     |                                                ^^^^ not found in this scope
     |
  help: consider importing this trait
     |
  1  + use core::marker::Sync;
     |

  error[E0405]: cannot find trait `Send` in this scope
    --> /Users/loris/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/thiserror-1.0.69/src/aserror.rs:48:33
     |
  48 | impl<'a> Sealed for dyn Error + Send + 'a {}
     |                                 ^^^^ not found in this scope
     |
  help: consider importing this trait
     |
  1  + use core::marker::Send;
     |

  error[E0405]: cannot find trait `Send` in this scope
    --> /Users/loris/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/thiserror-1.0.69/src/aserror.rs:49:33
     |
  49 | impl<'a> Sealed for dyn Error + Send + Sync + 'a {}
     |                                 ^^^^ not found in this scope
     |
  help: consider importing this trait
     |
  1  + use core::marker::Send;
     |

  error[E0405]: cannot find trait `Sync` in this scope
    --> /Users/loris/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/thiserror-1.0.69/src/aserror.rs:49:40
     |
  49 | impl<'a> Sealed for dyn Error + Send + Sync + 'a {}
     |                                        ^^^^ not found in this scope
     |
  help: consider importing this trait
     |
  1  + use core::marker::Sync;
     |

  error[E0405]: cannot find trait `Send` in this scope
    --> /Users/loris/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/thiserror-1.0.69/src/aserror.rs:50:33
     |
  50 | impl<'a> Sealed for dyn Error + Send + Sync + UnwindSafe + 'a {}
     |                                 ^^^^ not found in this scope
     |
  help: consider importing this trait
     |
  1  + use core::marker::Send;
     |

  error[E0405]: cannot find trait `Sync` in this scope
    --> /Users/loris/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/thiserror-1.0.69/src/aserror.rs:50:40
     |
  50 | impl<'a> Sealed for dyn Error + Send + Sync + UnwindSafe + 'a {}
     |                                        ^^^^ not found in this scope
     |
  help: consider importing this trait
     |
  1  + use core::marker::Sync;
     |

  Some errors have detailed explanations: E0405, E0463.
  For more information about an error, try `rustc --explain E0405`.
  error: could not compile `thiserror` (lib) due to 13 previous errors
  warning: build failed, waiting for other jobs to finish...
warning: build failed, waiting for other jobs to finish...
```

The build was working correctly with 2412-6 and the issue started to appears only after upgrading, also when skipping the WASM build, it works:

```
SKIP_WASM_BUILD= cargo build -p node-subtensor-runtime
```

The rust version used is `1.85` with `wasmv1-none`

### Steps to reproduce

- Clone the [following repo](https://github.com/opentensor/subtensor.git) 
- Try to build the branch `upgrade-polkadot-sdk-2503-7`.

**Comment by bkchr** [comment]
`thiserror` should not be enabled in `no-std`. Best to check where this is coming from, maybe you have forgot to disable the `std` feature somewhere.

**Comment by lorismoulin** [comment]
Issue was on my side, thanks @bkchr
